const gameProviders = {
  "1x2 Gaming": "G1X2",
  Amatic: "AMATIC",
  Azuretech: "YAT",
  Beefee: "BFG",
  "Bet Games TV": "BGT",
  "Big Time Gaming": "BTG",
  BGaming: "BGM",
  Blueprint: "BP",
  "Bombay Live": "BMB",
  Booming: "BOOMING",
  "Casino Technology": "CT",
  Edict: "EDICT",
  "E-Gaming": "EGAM",
  EGT: "EGT",
  Elk: "ELK",
  Endorphina: "ENDOR",
  Evolution: "EVOLD",
  Evoplay: "EVP",
  Ezugi: "EZUGI",
  Fazi: "FAZI",
  FBM: "FBM",
  GameArt: "GART",
  Greentube: "GTB",
  Habanero: "HBN",
  Hacksaw: "HKS",
  High5Games: "HI5",
  IGT: "IGT",
  Inspired: "INS",
  iSoftBet: "ISOFT",
  Kajot: "KAJ",
  Kalamba: "KAL",
  MGA: "MGA",
  Microgaming: "MGS",
  Netent: "NETEE",
  NoLimitCity: "NLC",
  OneTouch: "ONT",
  Playngo: "PNG",
  Playson: "PLS",
  "Pragmatic Play": "PP",
  Push: "PUSH",
  Quickspin: "QS",
  Realistic: "REALISTIC",
  "Red Rake": "RRG",
  "Red Tiger": "RTG",
  Relax: "RELAX",
  "Silver Bullet": "SBLT",
  Rubiplay: "RP",
  Skywind: "SW",
  Slingo: "SLG",
  Spinomenal: "SPN",
  Stakelogic: "STK",
  "Stakelogic LIVE": "STK2",
  Synot: "SYN",
  Swintt: "STT",
  "Tom Horn": "TOM",
  "Tom Horn 2": "TH2",
  "Wazdan (direct)": "WZD",
  "Wazdan (RB2)": "WD",
  Yggdrasil: "YGG",
  Zitro: "ZITRO",
};

const specialGameProviders = {
  Amatic: "AMATIC",
  Booming: "BOOMING",
  EGT: "EGT",
  Microgaming: "MGS",
  Fazi: "FAZI",
  GameArt: "GART",
  Realistic: "REALISTIC",
  TomHorn: "TOM",
  Wazdan: "WD",
  Yggdrasil: "YGG",
};

export { gameProviders, specialGameProviders };
